import Header from '@/containers/header/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Playfair_Display } from 'next/font/google'
import Footer from '@/containers/footer/Footer'

const inter = Inter({ subsets: ['latin'] })
const playfair = Playfair_Display({subsets: ["latin"]})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={playfair.className}>
        <Header/>
        {children}
      <Footer/>
        </body>
    </html>
  )
}
